# Generated by Django 2.2.7 on 2019-12-09 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('paterno', models.CharField(max_length=100)),
                ('materno', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13, 'Error de logitud')])),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('pais_residencia', models.CharField(max_length=100)),
                ('estado_residencia', models.CharField(max_length=100)),
                ('municipio_residencia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=6)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(max_length=50)),
                ('matricula_administrativo', models.CharField(max_length=6, unique=True)),
                ('matricula_gremial', models.CharField(max_length=6, unique=True)),
                ('grado_max_estudios', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Bachillerato o Preparatoria', 'Bachillerato o Preparatoria'), ('Carrera Comercial', 'Carrera Comercial'), ('Carrera Técnica', 'Carrera Técnica'), ('Normal', 'Normal'), ('Normal Superior', 'Normal Superior'), ('Licenciatura', 'Licenciatura'), ('Pasante de Carrera Profesional', 'Pasante de Carrera Profesional'), ('Especialidad', 'Especialidad'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('Pasante de Maestría', 'Pasante de Maestría'), ('Candidato a Doctor', 'Candidato a Doctor'), ('Postdoctorado', 'Postdoctorado')], max_length=60)),
                ('nss', models.CharField(max_length=11)),
                ('no_issste', models.CharField(max_length=50)),
                ('validado_renapo', models.BooleanField(null=True)),
                ('validado_siri', models.BooleanField(null=True)),
                ('alta_usuario', models.CharField(max_length=10)),
                ('alta_fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.Trabajador')),
            ],
        ),
    ]
