# Generated by Django 2.2.7 on 2019-11-28 01:29


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buscar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('paterno', models.CharField(max_length=100)),
                ('materno', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('pais_nacimiento', models.CharField(max_length=100)),
                ('estado_nacimiento', models.PositiveSmallIntegerField()),
                ('municipio_nacimiento', models.PositiveSmallIntegerField()),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('pais_residencia', models.CharField(max_length=100)),
                ('estado_residencia', models.PositiveSmallIntegerField()),
                ('municipio_residencia', models.PositiveSmallIntegerField()),
                ('localidad_reside', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=6)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
