# Generated by Django 2.2.10 on 2020-03-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='alta_usuario',
            field=models.CharField(max_length=150),
        ),
    ]
