# Generated by Django 2.2.7 on 2019-11-28 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0002_auto_20191128_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='rfc',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13, 'Error de logitud')]),
        ),
    ]
